### PR TITLE
Add window.exe steps to publish-release.yml

### PR DESCRIPTION
**Pull request by chaeh03**
## Description
This PR adds a new workflow to automate the release process for Windows executable files. The `publish-release.yml` file has been created in the `.github/workflows` directory to define the steps for building and publishing a Windows `.exe` file as part of the release process. This includes defining the build steps and ensuring that the `.exe` file is included in the GitHub release when a new tag is pushed.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [x] Refactoring, Maintenance
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by soimkim** [comment]
팀원분들의 리뷰가 필요합니다. 😃

**Comment by soonhong99** [comment]
image
제가 git release 실행하면 다음과 같은 에러가 발생하네요

**Comment by soimkim** [comment]
@chaeh03 , conflict 해결 부탁드립니다.

**Comment by soimkim** [comment]
https://github.com/fosslight/fosslight_scanner_gui/pull/12 로 Merge되어 본 PR은 close합니다.

**Pull request closed without merging**
