### PR TITLE
Enhance Release Process: Implement Version Tagging and macOS GUI App Zip Build

### PR DESCRIPTION
**Pull request by soonhong99**
## Description

This pull request addresses two key improvements to our release process for the FOSSLight GUI application:

## **Version Tagging in Release Archives:**

Modified the build process to incorporate the Git release tag version into the names of the generated tar.gz and zip files.
This change ensures that each release artifact clearly displays its corresponding version, improving traceability and user convenience.
Implementation: Updated the GitHub Actions workflow to extract the release tag and use it in the artifact naming convention.

## **macOS GUI App Zip Build Implementation:**

Implemented a new build process to create a zip archive specifically for the macOS GUI application.
This addition allows macOS users to easily download and use our application without complex installation procedures.
Implementation details:

Added a new step in the GitHub Actions workflow for macOS builds.
Utilized the ditto command to create a properly structured zip file that preserves the .app bundle structure.
Ensured that the resulting zip file can be directly unpacked and run on macOS systems.

These changes significantly improve our release management and user experience, particularly for macOS users. The version tagging enhancement applies to all platforms, ensuring consistency across our release artifacts.

## **Testing:**

Verified that the release artifacts now include the correct version tag in their filenames.
Tested the macOS zip file by unpacking and running the application on multiple macOS versions to ensure compatibility.
**_You need GH_TOKEN in action secret_**. GH_TOKEN is token that you issued from github.
if you can see [fosslight-gui-macos-setup-1.7.47.zip] and [fosslight-gui-ubuntu-setup-1.7.47.tar.gz] this format when you release in your repository, then you succeed.

## **Next steps:**
- Investigate and resolve the issue with the automatically generated draft releases created by electron-builder's publish action during the release process.
- Debug and fix the problem with the arm64 build of FOSSLight GUI, which currently shows a "damaged file" message and fails to run on M1 Macs.
  * Verify the release process to ensure the arm64 build is being correctly generated and packaged.
  * Investigate potential causes for the file damage, including code signing issues, packaging problems, or macOS security restrictions.
- Address the issue with the universal build, which currently crashes at the "Getting Ready" stage after launch.
  * Perform thorough testing and debugging to identify the cause of the crash.
  * Implement necessary fixes to ensure stable operation across different Mac architectures.
- Review and potentially revise the code signing and notarization process for macOS builds to eliminate "untrusted app" warnings.
- Conduct comprehensive testing on various macOS versions and architectures (Intel and Apple Silicon) to ensure consistent performance and stability.
- Update the build and release documentation to include any new processes or troubleshooting steps discovered during the resolution of these issues.

Please review these changes and let me know if any further modifications or clarifications are needed.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Refactoring, Maintenance
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by soonhong99** [comment]
https://github.com/fosslight/fosslight_scanner_gui/pull/8
해당 PR 인용하였습니다.

추가사항
1. release시 build되는 압축 파일명에 태그 버전 추가
2. mac os app build -> zip파일 압축해제시 fosslight_gui.app 생성되지만 getting ready... 상태

**Comment by ParkSangsin** [comment]
DCO 체크에 실패했는데, Commit 확인 부탁드립니다!

**Review by persi0815 — APPROVED** [review]

**Comment by soonhong99** [comment]
제가 한 커밋은 모두 -s 체크를했는데, 앞에 있는 커밋이 체크가 되지 않아 발생하는 오류같네요 ㅠㅠ 해당부분은 어떻게 해야할지 여쭤보겠습니다

**Comment by soonhong99** [comment]
CMD_BUILD 과정 제거 이유: 폴더명에 release된 버전명을 적기위해

**Comment by soonhong99** [comment]
스크린샷 2024-09-10 오후 11 02 29
electron-builder에서 draft되는 파일들

**Comment by soonhong99** [comment]
스크린샷 2024-09-10 오후 10 59 40
GH_TOKEN or GitHub Personal Access Token이 없으면 생기는 에러

**Comment by soonhong99** [comment]
```
publish:
  provider: github
  protocol: https
  owner: fosslight
  repo: fosslight_scanner_gui
  releaseType: draft
  publishAutoUpdate: true
```
electron-builder.yml 파일을 다음과 같이 바꿔도 제 GH_TOKEN을 넣고 하면 제 repo에 생성되네요.
그리고 v0.0.0-alpha.2 버전으로 한번 draft를 하고, 해당 버전으로 또다시 draft를 하려고 하면 
기존 pre-release를 draft로 변경하는 것을 허용하지 않아 충돌이 발생합니다.
따라서 배포 스크립트를 수정하여 기존 pre-release를 업데이트하도록 설정하거나 
기존 GitHub 릴리스를 삭제하고 새로 배포를 시도해야 합니다.

**Comment by soimkim** [comment]
windows도 PR 머지되면 테스트용으로 릴리즈할께요. 😄

**Pull request merged**
